#include "neon_recall/GameModel.hpp"
#include <algorithm>
#include <cmath>
#include <queue>

namespace neon {
static constexpr std::array<Cell,4> dirs{{{1,0},{0,1},{-1,0},{0,-1}}};
static std::vector<Cell> bfs(const std::array<bool,Maze::Width*Maze::Height>& open,Cell s,Cell goal){
  auto idx=[](Cell c){return c.y*Maze::Width+c.x;};std::array<int,Maze::Width*Maze::Height> parent;parent.fill(-2);std::queue<Cell>q;q.push(s);parent[idx(s)]=-1;
  while(!q.empty()){Cell c=q.front();q.pop();if(c==goal)break;for(Cell d:dirs){Cell n{c.x+d.x,c.y+d.y};if(n.x<0||n.y<0||n.x>=Maze::Width||n.y>=Maze::Height||!open[idx(n)]||parent[idx(n)]!=-2)continue;parent[idx(n)]=idx(c);q.push(n);}}
  if(parent[idx(goal)]==-2)return{};std::vector<Cell>out;for(int at=idx(goal);at!=-1;at=parent[at])out.push_back({at%Maze::Width,at/Maze::Width});std::reverse(out.begin(),out.end());return out;
}
void Maze::generate(std::mt19937_64&rng,int round){open_.fill(false);poison_.fill(false);starts_={Cell{1,13},Cell{19,13}};treasure_={10,7};
  // Iterative randomized depth-first carving on odd cells creates one readable,
  // fully connected maze. Extra loops increase later-round route ambiguity.
  std::vector<Cell> stack{{1,13}};open_[index(stack.back())]=true;
  while(!stack.empty()){Cell c=stack.back();std::vector<Cell>next;for(Cell d:dirs){Cell n{c.x+d.x*2,c.y+d.y*2};if(n.x>0&&n.y>0&&n.x<Width-1&&n.y<Height-1&&!open_[index(n)])next.push_back(n);}if(next.empty()){stack.pop_back();continue;}Cell n=next[rng()%next.size()];open_[index({(c.x+n.x)/2,(c.y+n.y)/2})]=true;open_[index(n)]=true;stack.push_back(n);}
  // Connect the even-x central vault and the opposite spawn to the maze.
  open_[index(treasure_)]=true;open_[index({9,7})]=true;open_[index({11,7})]=true;open_[index(starts_[1])]=true;open_[index({18,13})]=true;
  int loops=std::min(14,2+round);for(int i=0;i<loops;i++){int x=1+(int)(rng()%(Width-2)),y=1+(int)(rng()%(Height-2));Cell c{x,y};if(!open_[index(c)]&&((open_[index({x-1,y})]&&open_[index({x+1,y})])||(open_[index({x,y-1})]&&open_[index({x,y+1})])))open_[index(c)]=true;}
  solutions_[0]=bfs(open_,starts_[0],treasure_);solutions_[1]=bfs(open_,starts_[1],treasure_);refreshPoison(rng,round,1);
}
void Maze::refreshPoison(std::mt19937_64&rng,int round,int frame){poison_.fill(false);struct Candidate{Cell c;int score;std::uint64_t tie;};std::vector<Candidate>candidates;
 for(int y=1;y<Height-1;y++)for(int x=1;x<Width-1;x++){Cell c{x,y};if(!open(c)||c==treasure_||c==starts_[0]||c==starts_[1])continue;int score=0;bool p0=std::find(solutions_[0].begin()+std::min<size_t>(3,solutions_[0].size()),solutions_[0].end(),c)!=solutions_[0].end();bool p1=std::find(solutions_[1].begin()+std::min<size_t>(3,solutions_[1].size()),solutions_[1].end(),c)!=solutions_[1].end();score+=(p0?5:0)+(p1?5:0);int exits=0;for(Cell d:dirs)if(open({x+d.x,y+d.y}))++exits;if(exits>=3)score+=3;if(std::abs(x-treasure_.x)+std::abs(y-treasure_.y)<5)score+=2;candidates.push_back({c,score,rng()});}
 std::sort(candidates.begin(),candidates.end(),[](const Candidate&a,const Candidate&b){return a.score!=b.score?a.score>b.score:a.tie<b.tie;});int target=std::min((int)candidates.size(),std::min(12,3+round+frame)),placed=0;
 // Greedily prefer strategically relevant tiles, but reject every candidate
 // that would remove the last completely safe route for either player.
 for(const Candidate&candidate:candidates){if(placed>=target)break;poison_[index(candidate.c)]=true;if(!hasPoisonFreeRoute(0)||!hasPoisonFreeRoute(1))poison_[index(candidate.c)]=false;else ++placed;}
}
bool Maze::open(Cell c)const{return valid(c)&&open_[index(c)];}bool Maze::poison(Cell c)const{return valid(c)&&poison_[index(c)];}void Maze::setPoison(Cell c,bool v){if(valid(c)&&open(c))poison_[index(c)]=v;}int Maze::poisonCount()const{return(int)std::count(poison_.begin(),poison_.end(),true);}
bool Maze::hasPoisonFreeRoute(int player)const{if(player<0||player>1)return false;std::array<bool,Width*Height>seen{};std::queue<Cell>q;q.push(starts_[player]);seen[index(starts_[player])]=true;while(!q.empty()){Cell c=q.front();q.pop();if(c==treasure_)return true;for(Cell d:dirs){Cell n{c.x+d.x,c.y+d.y};if(valid(n)&&open(n)&&!poison(n)&&!seen[index(n)]){seen[index(n)]=true;q.push(n);}}}return false;}
std::uint64_t Maze::topologySignature()const{std::uint64_t hash=1469598103934665603ULL;for(bool cell:open_){hash^=cell?1ULL:0ULL;hash*=1099511628211ULL;}hash^=static_cast<std::uint64_t>(treasure_.x+treasure_.y*Width);return hash;}
const std::vector<Buff>& buffCatalogue(){static const std::vector<Buff>b={
 {BuffType::Shield,"Prism Shield","Block the next poison hit.","COMMON"},{BuffType::ExtraHeart,"Heart Cache","Gain one maximum heart now.","COMMON"},{BuffType::FleetFeet,"Phase Boots","Move 12% faster in blackout.","RARE"},{BuffType::LongMemory,"Slow Eclipse","Reveal lasts 0.7 seconds longer.","RARE"},{BuffType::EchoPulse,"Echo Pulse","Briefly flash nearby walls every few moves.","RARE"},{BuffType::Antidote,"Antidote","Poison hurts but no longer resets position.","EPIC"},{BuffType::SecondWind,"Second Wind","Survive one elimination with one heart.","EPIC"},{BuffType::TrailSense,"Afterimage","Your last three steps glow during blackout.","RARE"},{BuffType::TreasureSense,"Vault Signal","A faint compass points toward the treasure.","EPIC"}};return b;}
GameModel::GameModel(std::uint64_t seed):rng_(seed),seed_(seed){}
void GameModel::start(Mode m,int rounds,bool buffs){mode_=m;totalRounds_=std::clamp(rounds,1,15);soloBuffs_=buffs;round_=1;winner_=-1;players_={};players_[0].score=players_[1].score=0;players_[0].roundWins=players_[1].roundWins=0;beginRound();}
float GameModel::revealDuration()const{return std::max(1.8f,3.6f-round_*.12f)+players_[0].memoryBonus;}
float GameModel::blackoutDuration()const{return std::max(4.5f,7.5f-round_*.15f);}
void GameModel::beginRound(){frame_=1;framesPerRound_=std::min(7,4+round_/3);maze_.generate(rng_,round_);for(int i=0;i<2;i++){players_[i].pos=players_[i].start=maze_.start(i);players_[i].health=players_[i].maxHealth;players_[i].finished=players_[i].eliminated=false;players_[i].moveCooldown=0;players_[i].recent.clear();}phase_=Phase::Reveal;phaseTime_=revealDuration();firstFinisher_=-1;finishGrace_=0;roundMessage_="Study the maze and choose your own safe route";}
void GameModel::forceBlackout(){if(phase_==Phase::Reveal){phase_=Phase::Blackout;phaseTime_=blackoutDuration();roundMessage_="BLACKOUT - trust your memory";}}
void GameModel::update(float dt){dt=std::clamp(dt,0.f,.1f);for(auto&p:players_)p.moveCooldown=std::max(0.f,p.moveCooldown-dt);if(phase_==Phase::Reveal){phaseTime_-=dt;if(phaseTime_<=0)forceBlackout();}else if(phase_==Phase::Blackout){phaseTime_-=dt;if(firstFinisher_>=0)finishGrace_-=dt;bool both=mode_==Mode::Solo?players_[0].finished||players_[0].eliminated:(players_[0].finished||players_[0].eliminated)&&(players_[1].finished||players_[1].eliminated);if(both||(firstFinisher_>=0&&finishGrace_<=0)){finishRound();}else if(phaseTime_<=0){if(frame_<framesPerRound_){++frame_;maze_.refreshPoison(rng_,round_,frame_);phase_=Phase::Reveal;phaseTime_=revealDuration();roundMessage_="Poison shifted - study the maze again";}else finishRound();}}}
bool GameModel::move(int who,Cell d){if(phase_!=Phase::Blackout||who<0||who>(mode_==Mode::Solo?0:1))return false;Player&p=players_[who];if(p.finished||p.eliminated||p.moveCooldown>0)return false;Cell n{p.pos.x+d.x,p.pos.y+d.y};p.moveCooldown=.135f/p.speedMultiplier;if(!maze_.open(n))return false;p.recent.push_back(p.pos);if(p.recent.size()>3)p.recent.erase(p.recent.begin());p.pos=n;
 if(maze_.poison(n)){maze_.setPoison(n,false);if(p.shields>0)--p.shields;else{--p.health;if(!p.antidote)p.pos=p.start;if(p.health<=0){if(p.secondWind){p.secondWind=false;p.health=1;p.pos=p.start;}else p.eliminated=true;}}}
 if(p.pos==maze_.treasure()){p.finished=true;if(firstFinisher_<0){firstFinisher_=who;finishGrace_=mode_==Mode::Solo?0.f:5.f;}}
 return true;}
void GameModel::finishRound(){phase_=Phase::RoundResult;int first=firstFinisher_;if(mode_==Mode::Solo){if(players_[0].finished){players_[0].score+=1000+(int)(phaseTime_*20)+players_[0].health*100;players_[0].roundWins++;roundMessage_="Vault reached - memory intact!";}else roundMessage_="The vault faded before you arrived";}else{if(first>=0){players_[first].score+=1000+players_[first].health*100;players_[first].roundWins++;int other=1-first;if(players_[other].finished)players_[other].score+=600;else players_[other].score+=200;roundMessage_="Player "+std::to_string(first+1)+" reached the vault first!";}else{players_[0].score+=100;players_[1].score+=100;roundMessage_="The darkness defeated both runners";}}}
void GameModel::continueFromResult(){if(phase_!=Phase::RoundResult)return;if(round_>=totalRounds_){phase_=Phase::MatchResult;winner_=players_[0].score==players_[1].score?-1:(players_[0].score>players_[1].score?0:1);return;}if(mode_==Mode::Solo&&!soloBuffs_){++round_;beginRound();return;}prepareDraft();}
void GameModel::prepareDraft(){phase_=Phase::Draft;offers_.clear();draftingPlayer_=mode_==Mode::Solo?0:(firstFinisher_>=0?firstFinisher_:round_%2);draftsRemaining_=mode_==Mode::Solo?1:2;auto cat=buffCatalogue();std::vector<int>ids;for(int i=0;i<(int)cat.size();i++)if(mode_==Mode::Solo||cat[i].type!=BuffType::LongMemory)ids.push_back(i);std::shuffle(ids.begin(),ids.end(),rng_);int offerCount=totalRounds_<=3?2:totalRounds_<=7?3:4;for(int i=0;i<offerCount;i++)offers_.push_back(cat[ids[i]]);}
void GameModel::applyBuff(Player&p,BuffType t){switch(t){case BuffType::Shield:p.shields++;break;case BuffType::ExtraHeart:p.maxHealth++;break;case BuffType::FleetFeet:p.speedMultiplier*=1.12f;break;case BuffType::LongMemory:p.memoryBonus+=.7f;break;case BuffType::EchoPulse:p.echoTimer=1;break;case BuffType::Antidote:p.antidote=true;break;case BuffType::SecondWind:p.secondWind=true;break;case BuffType::TrailSense:p.trailSense=true;break;case BuffType::TreasureSense:p.treasureSense=true;break;}}
bool GameModel::chooseBuff(int i){if(phase_!=Phase::Draft||i<0||i>=(int)offers_.size())return false;applyBuff(players_[draftingPlayer_],offers_[i].type);if(--draftsRemaining_>0){draftingPlayer_=1-draftingPlayer_;auto cat=buffCatalogue();std::vector<int>ids;for(int n=0;n<(int)cat.size();n++)if(cat[n].type!=BuffType::LongMemory)ids.push_back(n);std::shuffle(ids.begin(),ids.end(),rng_);int count=totalRounds_<=3?2:totalRounds_<=7?3:4;offers_.clear();for(int n=0;n<count;n++)offers_.push_back(cat[ids[n]]);return true;}++round_;beginRound();return true;}
std::vector<Cell> GameModel::shortest(Cell,Cell)const{return{};}
}
